/* Automatically generated nanopb header */
/* Generated by nanopb-1.0.0-dev */

#ifndef PB_PROTOLINK__GEOMETRY_MSGS__VECTOR3_PROTO_GEOMETRY_MSGS__VECTOR3_PB_H_INCLUDED
#define PB_PROTOLINK__GEOMETRY_MSGS__VECTOR3_PROTO_GEOMETRY_MSGS__VECTOR3_PB_H_INCLUDED
#include <pb.h>

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Struct definitions */
typedef struct _protolink__geometry_msgs__Vector3_geometry_msgs__Vector3 {
    bool has_x;
    double x;
    bool has_y;
    double y;
    bool has_z;
    double z;
} protolink__geometry_msgs__Vector3_geometry_msgs__Vector3;


#ifdef __cplusplus
extern "C" {
#endif

/* Initializer values for message structs */
#define protolink__geometry_msgs__Vector3_geometry_msgs__Vector3_init_default {false, 0, false, 0, false, 0}
#define protolink__geometry_msgs__Vector3_geometry_msgs__Vector3_init_zero {false, 0, false, 0, false, 0}

/* Field tags (for use in manual encoding/decoding) */
#define protolink__geometry_msgs__Vector3_geometry_msgs__Vector3_x_tag 1
#define protolink__geometry_msgs__Vector3_geometry_msgs__Vector3_y_tag 2
#define protolink__geometry_msgs__Vector3_geometry_msgs__Vector3_z_tag 3

/* Struct field encoding specification for nanopb */
#define protolink__geometry_msgs__Vector3_geometry_msgs__Vector3_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, DOUBLE,   x,                 1) \
X(a, STATIC,   OPTIONAL, DOUBLE,   y,                 2) \
X(a, STATIC,   OPTIONAL, DOUBLE,   z,                 3)
#define protolink__geometry_msgs__Vector3_geometry_msgs__Vector3_CALLBACK NULL
#define protolink__geometry_msgs__Vector3_geometry_msgs__Vector3_DEFAULT NULL

extern const pb_msgdesc_t protolink__geometry_msgs__Vector3_geometry_msgs__Vector3_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define protolink__geometry_msgs__Vector3_geometry_msgs__Vector3_fields &protolink__geometry_msgs__Vector3_geometry_msgs__Vector3_msg

/* Maximum encoded size of messages (where known) */
#define PROTOLINK__GEOMETRY_MSGS__VECTOR3_PROTO_GEOMETRY_MSGS__VECTOR3_PB_H_MAX_SIZE protolink__geometry_msgs__Vector3_geometry_msgs__Vector3_size
#define protolink__geometry_msgs__Vector3_geometry_msgs__Vector3_size 27

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
