/* Automatically generated nanopb header */
/* Generated by nanopb-1.0.0-dev */

#ifndef PB_PROTOLINK__STD_MSGS__STRING_PROTO_STD_MSGS__STRING_PB_H_INCLUDED
#define PB_PROTOLINK__STD_MSGS__STRING_PROTO_STD_MSGS__STRING_PB_H_INCLUDED
#include <pb.h>

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Struct definitions */
typedef struct _protolink__std_msgs__String_std_msgs__String {
    pb_callback_t data;
} protolink__std_msgs__String_std_msgs__String;


#ifdef __cplusplus
extern "C" {
#endif

/* Initializer values for message structs */
#define protolink__std_msgs__String_std_msgs__String_init_default {{{NULL}, NULL}}
#define protolink__std_msgs__String_std_msgs__String_init_zero {{{NULL}, NULL}}

/* Field tags (for use in manual encoding/decoding) */
#define protolink__std_msgs__String_std_msgs__String_data_tag 1

/* Struct field encoding specification for nanopb */
#define protolink__std_msgs__String_std_msgs__String_FIELDLIST(X, a) \
X(a, CALLBACK, OPTIONAL, STRING,   data,              1)
#define protolink__std_msgs__String_std_msgs__String_CALLBACK pb_default_field_callback
#define protolink__std_msgs__String_std_msgs__String_DEFAULT NULL

extern const pb_msgdesc_t protolink__std_msgs__String_std_msgs__String_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define protolink__std_msgs__String_std_msgs__String_fields &protolink__std_msgs__String_std_msgs__String_msg

/* Maximum encoded size of messages (where known) */
/* protolink__std_msgs__String_std_msgs__String_size depends on runtime parameters */

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
